// @flow
// flow-typed signature: 2b5dca68053a48c5307e873620783d24
// flow-typed version: <<STUB>>/immer_v3.1.3/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'immer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'immer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'immer/dist/immer' {
  declare module.exports: any;
}

declare module 'immer/dist/immer.module' {
  declare module.exports: any;
}

declare module 'immer/dist/immer.umd' {
  declare module.exports: any;
}

declare module 'immer/src/common' {
  declare module.exports: any;
}

declare module 'immer/src/es5' {
  declare module.exports: any;
}

declare module 'immer/src/immer' {
  declare module.exports: any;
}

declare module 'immer/src/index' {
  declare module.exports: any;
}

declare module 'immer/src/patches' {
  declare module.exports: any;
}

declare module 'immer/src/proxy' {
  declare module.exports: any;
}

declare module 'immer/src/scope' {
  declare module.exports: any;
}

// Filename aliases
declare module 'immer/dist/immer.js' {
  declare module.exports: $Exports<'immer/dist/immer'>;
}
declare module 'immer/dist/immer.module.js' {
  declare module.exports: $Exports<'immer/dist/immer.module'>;
}
declare module 'immer/dist/immer.umd.js' {
  declare module.exports: $Exports<'immer/dist/immer.umd'>;
}
declare module 'immer/src/common.js' {
  declare module.exports: $Exports<'immer/src/common'>;
}
declare module 'immer/src/es5.js' {
  declare module.exports: $Exports<'immer/src/es5'>;
}
declare module 'immer/src/immer.js' {
  declare module.exports: $Exports<'immer/src/immer'>;
}
declare module 'immer/src/index.js' {
  declare module.exports: $Exports<'immer/src/index'>;
}
declare module 'immer/src/patches.js' {
  declare module.exports: $Exports<'immer/src/patches'>;
}
declare module 'immer/src/proxy.js' {
  declare module.exports: $Exports<'immer/src/proxy'>;
}
declare module 'immer/src/scope.js' {
  declare module.exports: $Exports<'immer/src/scope'>;
}
